---
- name: fail when ruby user is not defined
  fail: msg="The ruby_user variable must be set."
  when: (ruby_user is not defined) or (not ruby_user)

# set facts to reliably determine os
- name: discover operating system
  include: discover/os.yml

# set facts to reliably determine ruby variables
- name: discover ruby
  include: discover/ruby.yml

# load per-os and per distro variables
- name: load variables
  include_vars: "{{ var_loop_item }}"
  with_items:
    - "{{ os_name }}/common.yml"
    - "{{ os_name }}/{{ os_release }}.yml"
  loop_control: { loop_var: var_loop_item }

# refresh cache on ubuntu
- name: refresh apt cache
  apt: update_cache=yes cache_valid_time=3600
  when: os_name == "ubuntu"
  become: true

# install build dependencies
- name: install git
  package: name=git state=present
  become: true

# install rbenv
- name: install rbenv
  include: rbenv.yml

# install ruby
- name: install ruby
  include: ruby.yml
